simple_back/accounts/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('provider/', views.ProviderView.as_view(), name='provider'),
    path('provider/update', views.ProviderProfileUpdateView.as_view(), name='provider_update'),
    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/update', views.CustomerProfileUpdateView.as_view(), name='customer_update'),
]

simple_back/simple_back/urls.py
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib import admin
from django.urls import re_path as url
from django.urls import include, path
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_service.urls')),
    path('', include('accounts.urls'))
]

schema_view = get_schema_view(
   openapi.Info(
      title="Auth_service API",
      default_version='v1',
      description="Документация для приложения simple_back",
      contact=openapi.Contact(email="lan2828@yandex.ru"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
   url(r'^swagger(?P<format>\.json|\.yaml)$',
       schema_view.without_ui(cache_timeout=0), name='schema-json'),
   url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
       name='schema-swagger-ui'),
   url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
       name='schema-redoc'),
]

simple_back/templates/customer.html
{% extends 'index.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <title>Заказчик</title>
{% endblock head %}

{% block content %}

<div class="center">
    <table>
    <tbody>
        <tr>
            <th>Имя</th>
            <td>{{ customer.name }}</td>
        </tr>
        <tr>
            <th>Контактные данные</th>
            <td>{{ customer.contact_data }}</td>
        </tr>
        <tr>
            <th>Специализация</th>
            <td>{{ customer.specialty }}</td>
        </tr>
        <tr>
            <th>Дополнительная информация</th>
            <td>{{ customer.info }}</td>
        </tr>
    </tbody>
</table>
</div>

<button onclick="window.location.href='{% url 'accounts:customer_update' %}'" class="edit-button">Редактировать</button>

{% endblock content %}

simple_back/templates/customer_edit.html
<!doctype html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head %}
        <title>Заказчик</title>
        <link rel="stylesheet" href="{% static 'index.css' %}">
        <link rel="stylesheet" href="{% static 'profile.css' %}">
    {% endblock head %}
</head>

<body>
    <header>
        <a href="{% url 'accounts:home' %}" class="logo">Наш сайт</a>
        <nav>
            <ul>
                <li><a href="{% url 'accounts:provider' %}">Заказчик</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}
    <div class="center">
        <form method="post" class="profile-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    </div>
    {% endblock content %}
</body>

</html>

simple_back/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head %}
        <title>Главная Страница</title>
        <link rel="stylesheet" href="{% static 'index.css' %}">
    {% endblock head %}
</head>

<body>

    <header>
        <a href="{% url 'accounts:home' %}" class="logo">Наш сайт</a>

        <nav>
            <ul>
                <li><a href="{% url 'accounts:customer' %}">Заказчик</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'accounts:provider' %}">Исполнитель</a></li>
            </ul>
        </nav>

    </header>

{% block content %}

{% endblock content %}

</body>
</html>

simple_back/templates/provider.html
{% extends 'index.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <title>Исполнитель</title>
{% endblock head %}

{% block content %}

<div class="center">
    <table>
    <tbody>
        <tr>
            <th>Имя</th>
            <td>{{ provider.name }}</td>
        </tr>
        <tr>
            <th>Контактные данные</th>
            <td>{{ provider.contact_data }}</td>
        </tr>
        <tr>
            <th>Специализация</th>
            <td>{{ provider.specialty }}</td>
        </tr>
        <tr>
            <th>Дополнительная информация</th>
            <td>{{ provider.info }}</td>
        </tr>
        <tr>
            <th>Опыт в годах</th>
            <td>{{ provider.experience_in_years }}</td>
        </tr>
    </tbody>
</table>
</div>

<button onclick="window.location.href='{% url 'accounts:provider_update' %}'" class="edit-button">Редактировать</button>

{% endblock content %}

simple_back/templates/provider_edit.html
<!doctype html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head %}
        <title>Исполнитель</title>
        <link rel="stylesheet" href="{% static 'index.css' %}">
        <link rel="stylesheet" href="{% static 'profile.css' %}">
    {% endblock head %}
</head>

<body>
    <header>
        <a href="{% url 'accounts:home' %}" class="logo">Наш сайт</a>
        <nav>
            <ul>
                <li><a href="{% url 'accounts:provider' %}">Исполнитель</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}
    <div class="center">
        <form method="post" class="profile-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    </div>
    {% endblock content %}
</body>

</html>